/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a_ponte;

import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Betim
 */
public class janela_caro extends javax.swing.JFrame {

    /**
     * Creates new form janela_caro
     */
    public janela_caro() {
       
        
        initComponents();
        setSize(650,550);
        novocar x = new novocar();
        x.getT(25,5);
        x.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Adicionar Carro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 290, 130, 30);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 20, 0, 0);

        jLabel1.setForeground(new java.awt.Color(255, 5, 5));
        jLabel1.setText("Tempo de travesia");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 230, 120, 20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(90, 250, 100, 30);

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Tempo de espera");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 230, 110, 14);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 250, 100, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a_ponte/p7irh6n6j186ih4s90k26o7g0tq7ok6ja.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 10, 640, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                novocar y = new novocar();
                y.getT(25,5);
                y.start();
                
//                Random v = new Random();
//                y.getT(v.nextInt(50)+1,v.nextInt(10)+1);//colocar as coisas do botão aqui
                
                
                System.out.println("umbó");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    
    public class novocar extends Thread{
        int x=0;
        int vx,te,i=1;
        boolean t=true;
        JLabel lcar = new JLabel(new ImageIcon(getClass().getResource("carro_medio.png")));
        
        public void getT(int vx,int te){
            this.vx = vx;
            this.te = te;
            
        }
        public int dir = 1;
        public void run() {
            adcar(lcar);
            
            ImageIcon iccarm = new ImageIcon(getClass().getResource("carro_medio.png"));
            JLabel lcarm = new JLabel(iccarm);
            ImageIcon iccarm1 = new ImageIcon(getClass().getResource("carro_medio1.png"));
            JLabel lcarm1 = new JLabel(iccarm1);
             
         
            while(t){
                try{Thread.sleep(vx);}catch(Exception erro){}
                lcar.setBounds(lcar.getX()+this.i, 150, 45, 20);
               if(x>10){
                lcar.setIcon(iccarm);
                x++;
                System.out.println(x);}
                if(x<=10|| x>20 ){
                lcar.setIcon(iccarm1);
                x++;
                System.out.println(x);
                }else x=0;            
                //lcar = new JLabel(new ImageIcon(getClass().getResource("carro_rapido.png")));
                if(lcar.getX()>=500 || lcar.getX()<=100){
                    i=-i;
                    try{Thread.sleep(te*1000);}catch(Exception erro){}
                   
                }    
            }
            
        }
        
    }     public void adcar(JLabel x){
          
        x.setBounds(100,150, 45, 20);
            add(x);
            jLabel3.add(x);
                

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janela_caro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janela_caro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janela_caro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janela_caro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new janela_caro().setVisible(true);
     
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
